* Control Groups

cgroups (aka control groups) is a Linux kernel feature to limit, police and
account the resource usage for a set of processes. It provides a mechanism for
aggregating/partitioning sets of tasks, and all their future children, into
hierarchical groups with specialized behaviour.

Compared to other approaches like the `nice` command or `limits.conf`, cgroups
are more flexible as they can operate on subsets of processes (possibly with
different system users).

** Definitions

A *cgroup* associates a set of tasks with a set of parameters for one or more
subsystems.

A *subsystem* is a module that treat groups of tasks in particular ways,
typically a "resource controller" that schedules a resource or applies
per-cgroup limits.

A *hierarchy* is a set of cgroups arranged in a tree. It is possible exist
multiple active hierarchies, each one is a partition of all tasks in the system.

User-level code may create and destroy cgroups by name in an instance of the
cgroup virtual file system, specify and query to which cgroup a task is
assigned, and list the task PIDs assigned to a cgroup.

A file system of type "cgroup" may be mounted, all support for querying and
modifying cgroups is via this cgroup file system.

Each cgroup is represented by a directory in the cgroup file system containing
the following files describing that cgroup:

- *tasks* list of tasks (by PID) attached to that cgroup.
- *cgroup.procs* list of thread group IDs in the cgroup.
- *notify_on_release* flag run the release agent on exit?
- *release_agent* the path to use for release notifications.
- Other subsystems such as *cpusets* may add additional files.

New cgroups are created using the mkdir system call or shell command.  The
properties of a cgroup, such as its flags, are modified by writing to the
appropriate file in that cgroups directory.

The use of a Linux virtual file system (vfs) to represent the cgroup hierarchy
provides for a familiar permission and name space for cgroups, with a minimum of
additional kernel code.

If the notify_on_release flag is enabled in a cgroup, then whenever the last
task in the cgroup leaves and the last child cgroup of that cgroup is removed,
then the kernel runs the command specified by the contents of the
"release_agent" file in that hierarchy's root directory.

If the clone_children flag is enabled in a cgroup, a new cpuset cgroup will copy
its configuration from the parent during initialization.

** Installation

The installation can be done using any of *libcgroup*, *cgmanager* or *systemd*.

** Usage

They can be used in multiple ways:

- By accessing the cgroup *filesystem* directly.
- Using the *cgm* client (part of the cgmanager).
- Via *cgcreate*, *cgexec* and *cgclassify* (part of the libcgroup).

To start a new job, using the *cpuset* cgroup subsystem, the steps are:

- Using the *filesystem*:

#+begin_src shell-script
  mount -t tmpfs cgroup_root /sys/fs/cgroup
  mkdir /sys/fs/cgroup/cpuset
  mount -t cgroup cpuset -ocpuset /sys/fs/cgroup/cpuset
  cd /sys/fs/cgroup/cpuset
  mkdir Foo
  cd Foo
  /bin/echo 2-3 > cpuset.cpus
  /bin/echo 1 > cpuset.mems
  /bin/echo $$ > tasks
  sh # The subshell 'sh' is now running in cgroup Foo
  cat /proc/self/cgroup
#+end_src

- Using *libcgroup* command line tools:

#+begin_src shell-script
  cgcreate -g memory,cpu:groupname/foo
  cgexec -g memory,cpu:groupname/foo bash
#+end_src

- Using *cgmanager*:

#+begin_src shell-script
  cgm create memory groupname/foo
  cgm create cpu    groupname/foo
  bash
  cgm movepid memory groupname/foo $pid_of_bash
  cgm movepid cpu    groupname/foo $pid_of_bash
#+end_src

To *limit the memory* usage of all processes in this group to 10 MB, run:

#+begin_src shell-script
  echo 10000000 > /sys/fs/cgroup/memory/groupname/foo/memory.limit_in_bytes
  # OR
  cgm setvalue memory groupname/foo memory.limit_in_bytes 10000000
#+end_src

Similarly you can *change the CPU priority* ("shares") of this group. By default
all groups have 1024 shares. A group with 100 shares will get a ~10% portion of
the CPU time:

#+begin_src shell-script
  echo 100 > /sys/fs/cgroup/cpu/groupname/foo/cpu.shares
#+end_src

You can also change the cgroup of already running processes

#+begin_src shell-script
  pidof bash
  # 13244 13266
  cgclassify -g memory,cpu:groupname/foo `pidof bash`
  cat /proc/13244/cgroup
  # 11:memory:/groupname/foo
  #  6:cpu:/groupname/foo
#+end_src

You can attach the current shell task by doing `echo 0 > tasks`.

You can use the cgroup.procs file instead of the tasks file to move all threads
in a threadgroup at once.

Since every task is always a member of exactly one cgroup in each hierarchy, to
remove a task from its current cgroup you must move it into a new cgroup
(possibly the root cgroup).

If you want your cgroups *to be created at boot*, you can define them in
*/etc/cgconfig.conf*:

#+begin_src
  group groupname/foo {
    cpu {
      cpu.shares = 100;
    }
    memory {
      memory.limit_in_bytes = 10000000;
    }
  }
#+end_src

** References

- https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt
- https://wiki.archlinux.org/index.php/cgroups
